
import type { Metadata } from "next";
import HeaderStyle1 from "@/components/Header/styles/style1";
import FooterStyle1 from "@/components/Footer/styles/style1";
import HeaderTopBar from "@/components/Header/header-top-bar";
import Marquee from "@/components/Header/marquee";
import { CartProvider } from "@/context/CartContext";
type Props = {
  children: React.ReactNode;
};



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({children}: Props) {
 

  return (
   
        <>
        <CartProvider>

            <Marquee/>
            <HeaderTopBar/>
            <HeaderStyle1 />
        
            {children}
            <FooterStyle1 />
        </CartProvider>
        </>
          
  
  );
}
