import type { Metadata } from "next";


type Props = {
  children: React.ReactNode;
};




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({children}: Props) {
 

  return (
    <>
    <div className='flex justify-center items-center h-screen'>

     <div className="max-w-md border  mx-auto text-center bg-white px-4 sm:px-8 py-10 rounded-xl shadow">
   
    {children}
   </div>
    </div>
    
    </>
     
       
    
  );
}
