import {NextIntlClientProvider} from 'next-intl';
import {cookies} from 'next/headers';
import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import HeaderStyle1 from "@/components/Header/styles/style1";
import FooterStyle1 from "@/components/Footer/styles/style1";
import "./globals.css";
import HeaderTopBar from "@/components/Header/header-top-bar";
import Marquee from "@/components/Header/marquee";
import { CartProvider } from "@/context/CartContext";
import { ThemeProvider } from "@/components/ThemeProvider";
type Props = {
  children: React.ReactNode;
};
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({children}: Props) {
  const store = await cookies();
  const locale = store.get('locale')?.value === 'ar' ? 'ar' : 'en';
  const dir = locale === 'ar' ? 'rtl' : 'ltr';
  
  // Load messages for the locale
  const messages = (await import(`../messages/${locale}.json`)).default;

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <body className={`${dir === 'rtl' ? 'font-rtl' : 'font-ltr'} ${geistMono.variable} min-h-screen flex flex-col`} >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider>
            <CartProvider>
        
            <Marquee/>
            <HeaderTopBar/>
            <HeaderStyle1 />
        
            <main className="flex-1 dark:bg-gray-900 bg-gray-50">
              {children}
            </main>
            
            <FooterStyle1 />
          
            </CartProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
