import {cookies} from 'next/headers';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


type Props = {
  children: React.ReactNode;
};
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({children}: Props) {
  const store = await cookies();
  const locale = store.get('locale')?.value === 'ar' ? 'ar' : 'en';
  const dir = locale === 'ar' ? 'rtl' : 'ltr';

  return (
    <html lang={locale} dir={dir}>
      <body className={`${dir === 'rtl' ? 'font-rtl' : 'font-ltr'} ${geistMono.variable}`}>
     
          {children}
       
      </body>
    </html>
  );
}
